### ISSUE TITLE
우우

### ISSUE THREAD

**Issue by diaa-woo** [Lovingcats/Flutter_study#1]
뭔 플러터 기초냐! 개쩌는 블루바이저 플러터 마스터답게 개쩌는 프로젝트나 만들어라!

**Comment by Lovingcats** [comment]
회사에서 플러터 쓰지 않습니다.. ㅠㅠ....

**Comment by diaa-woo** [comment]
하긴 블루바이저에서 플러터를 사용하면 조용제가 다 휘어잡을테니... 밸런스 조절이 필요하긴하다 ㅇㅈ

아무튼 조용제는 곧 토스 개발자됩니다. 이 이슈는 성지순례가 될거여 ㅅㄱ

**Comment by Lovingcats** [comment]
야!!!!!!!!!!!!!!!!
